title: "Things I Know"
description: "A growing list of knowledge, tips, and ideas I've learned."
author: "YOUR NAME"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
