title: "Things I Know"
description: "A growing collection of knowledge and ideas."
author: "Thomas Ashwin Varghese"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
paginate: 5
paginate_path: "/page:num/"

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Tags"
    url: /tags/
