title: "Things I Know"
description: "A personal collection of knowledge, projects, and my impossible list."
baseurl: "" 
url: "https://ashwinthomas143.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# For search.json
collections:
  posts:
    output: true

# Exclude default stuff
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]
